---
title: Marcus Relacion, Designer
timezone: America/New_York
collections:
  jobs:
    title: Jobs
    output: false
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: ''
    type: Projects
  values:
    layout: singles/single-project
- scope:
    path: ''
    type: jobs
  values:
    is-current: 
    job-duration: 
    job-title: 
- scope:
    path: ''
    type: projects
  values:
    is-featured: 
    project-year: 
    project-header-image: 
    project-excerpt-text: 
permalink: pretty
exclude:
- package.json
- gulpfile.js
- node_modules
- README.md
- Gemfile
- Gemfile.lock
- ".jekyll-metadata"
- ".sass-cache"
- CNAME
sass:
  sass_dir: _sass
  style: compressed
