---
title: Marcus Relacion, Designer
timezone: America/New_York
collections:
  case-studies:
    title: Case Studies
    output: true
  notes:
    title: Notes
    output: false
  photos:
    title: Photos
    output: true
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: ''
    type: jobs
  values:
    is-current: 
    job-duration: 
    job-title: 
- scope:
    path: ''
    type: projects
  values:
    layout: single/project
    main-content-text: 
    image: 
    description: 
    year: 
    excerpt: 
    client: 
    role: 
    collaborators: []
    skills: []
- scope:
    path: ''
    type: photos
  values:
    layout: single/photoset
    image: 
    description: 
    is-featured: 
    year: 
    excerpt: 
    location: 
permalink: pretty
exclude:
- package.json
- gulpfile.js
- node_modules
- README.md
- Gemfile
- Gemfile.lock
- ".jekyll-metadata"
- ".sass-cache"
- CNAME
- ".DS_Store"
sass:
  sass_dir: _sass
  style: compressed
logo-image: "/uploads/mr-white-logo.svg"
is-updating: true
update-message: "Currently, undergoing maintenance.  \U0001F6E0"
update-link: https://github.com/marcusrelacion/marcusrelacion.github.io/issues
