---
title: Marcus Relacion, Designer & Developer
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
    description: My thoughts and ideas
    feature_text: 'Welcome to the blog'
    feature_image: https://picsum.photos/2560/600?image=866
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
  values:
    image: 
exclude:
- package.json
- gulpfile.js
- node_modules
- README.md
- Gemfile
- Gemfile.lock
- ".jekyll-metadata"
- ".sass-cache"
- CNAME
- ".DS_Store"
plugins_dir:
- jekyll-feed
sass:
  sass_dir: _sass
  style: compressed
permalink: pretty
encoding: utf-8
lang: en-US
logo: 
description: Marcus Relacion is an East Coast based UI Designer currently living in
  Alexandria, VA.
url: https://marcusrelacion.com
baseurl: 
repo: https://github.com/marcusrelacion/marcusrelacion.github.io
email: hello@marcusrelacion.com
navigation_header: 
navigation_footer: 
social_links: 
