---
title: Marcus Relacion, Designer
timezone: America/New_York
collections:
  notes:
    title: Notes
    output: false
  photos:
    title: Photos
    output: false
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: ''
    type: jobs
  values:
    is-current: 
    job-duration: 
    job-title: 
- scope:
    path: ''
    type: projects
  values:
    layout: single/project
    year: 
    image: 
    main-content-text: 
    client: 
    role: 
    collaborators: []
    skills: []
- scope:
    path: ''
    type: photos
  values:
    layout: single/photoset
    year: 
    image: 
    main-content-text: 
    location: 
permalink: pretty
sass:
  sass_dir: _sass
  style: compressed
profile-image: "/uploads/mr-photo.jpg"
logo-image: "/uploads/mr-white-logo.svg"
is-updating: true
update-message: "Currently, undergoing maintenance.  \U0001F6E0"
update-link: https://github.com/marcusrelacion/marcusrelacion.github.io/issues
markdown: kramdown
gems:
- jekyll-feed
introduction-header: "Hello! \U0001F44B\U0001F3FE"
introduction-subheader: "I'm Marcus Relacion, a designer and front-end developer from
  Washington, DC. \n\n<mark class=\"pa1 br1 bg-mr-primary white f5 f4-ns\">Currently
  a UI Designer at <a class=\"white\" href=\"http://www.clarabridge.com\" target=\"_blank\">Clarabridge</a>.</mark>\n"
introduction-image: "/assets/imgs/mr-portrait.jpg"
introduction-image-alt: Portrait of Marcus Relacion, designer and developer from Washington,
  DC
projects-header: Projects
projects-subheader: 'Take a moment to view the project I’ve had the opportunity to
  work on over the years.

'
projects-archive-link: "/projects/"
projects-image: "/assets/imgs/hero-work.jpg"
about-header: About
about-subheader: "I'm currently living in Washington, DC and working as a UI Designer
  at Clarabridge. Previously, I worked as a Designer at TrackMaven. \n\nOutside of
  work, I spend the bulk of my time taking photographs, spending time with friends
  and family and gaming.\n"
about-image: "/assets/imgs/hero-about.jpg"
about-image-alt: Portrait of Marcus Relacion, designer and developer from Washington,
  DC
about-resume: https://siteleaf-cdn.s3.amazonaws.com/570e4dce3420fe01a900032f/assets/5717af4c3420fe073d000161.pdf?X-Amz-Expires=600&X-Amz-Date=20170731T021724Z&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAI2QYAGBXKTUSU2MA/20170731/us-east-1/s3/aws4_request&X-Amz-SignedHeaders=host&X-Amz-Signature=efff05bff2a0202b501064d335ce9eac442ac427d3f26d6fdaeae53fa19c4059
copyright: 2017 &amp; beyond, Marcus Relacion
exclude:
- package.json
- gulpfile.js
- node_modules
- README.md
- Gemfile
- Gemfile.lock
- ".jekyll-metadata"
- ".sass-cache"
- CNAME
- ".DS_Store"
