# Site configuration
# 1. Files excluded from Jekyll builds
# 2. Installed Gems
# 3. Gem settings
# 4. Jekyll settings
# 5. Collections
# 6. Jekyll collections settings
# 7. Site settings
# 8. Site navigation

# 1. Files excluded from Jekyll builds
exclude:
- package.json
- gulpfile.js
- node_modules
- README.md
- Gemfile
- Gemfile.lock
- ".jekyll-metadata"
- ".sass-cache"
- CNAME
- ".DS_Store"

# 2. Installed Gems
plugins_dir:
- jekyll-feed

# 3. Gem settings

# 4. Jekyll settings
sass:
  sass_dir: _sass
  style: compressed # Style compression
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
timezone: America/New_York # Timezone for blog posts and alike

# 5. Collections
collections:
  posts:
    title: Posts # Needed for Siteleaf
    output: true
    description: "My thoughts and ideas" # The post list page content
    feature_text: |
      Welcome to the blog
    feature_image: "https://picsum.photos/2560/600?image=866"
  uploads:
    title: Uploads
    output: true

# 6. Jekyll collections settings
defaults:
  -
    scope:
      path: ""
    values:
      image: # Default image for sharing

# 7. Site settings
encoding: utf-8 # Make sure the encoding is right
lang: en-US # Set the site language
title: "Marcus Relacion, Designer & Developer" # Site name or title, also used in jekyll-seo-tag
logo:  # Site logo, also used in jekyll-seo-tag
description: "Marcus Relacion is an East Coast based UI Designer currently living in Alexandria, VA." # Site description and default description, also used in jekyll-seo-tag
url: "https://marcusrelacion.com" # Site url, also used in jekyll-seo-tag
baseurl: ""
repo: "https://github.com/marcusrelacion/marcusrelacion.github.io"
email: "hello@marcusrelacion.com"

# 8. Site navigation
navigation_header:
navigation_footer:
social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired