# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
---
# Site Title
title: Marcus Relacion | Designer & Developer

# Site Description
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Site URLs
assets-url: https://assets.marcusrelacion.com

# Collections
collections:
  notes:
    output: true
    permalink: /notes/:path//?

  projects:
    output: true
    permalink: /projects/:path/

defaults:
  scope:
    type: projects
    values:
      title: ""
      description: ""
      hero-image: ""
      og-image: ""
      layout: single/post

# Build settings
markdown: kramdown

# Sass Settings
sass:
  sass_dir: _sass
  style: compressed

# Included Gems
gems:
  - jekyll-feed

# Card Content

# Introduction 
introduction-header: "Hello! 👋🏾"
introduction-subheader: |
  I'm Marcus Relacion, a designer and front-end developer from Washington, DC. 
  
  <mark class="pa1 br1 bg-mr-primary white f5 f4-ns">Currently a UI Designer at <a class="white" href="http://www.clarabridge.com" target="_blank">Clarabridge</a>.</mark>
introduction-image: /assets/imgs/mr-portrait.jpg
introduction-image-alt: Portrait of Marcus Relacion, designer and developer from Washington, DC

# Projects
projects-header: Projects
projects-subheader: |
  Take a moment to view the project I’ve had the opportunity to work on over the years.
projects-archive-link: /projects/
projects-image: /assets/imgs/hero-work.jpg

# About
about-header: About
about-subheader: | 
  I'm currently living in Washington, DC and working as a UI Designer at Clarabridge. Previously, I worked as a Designer at TrackMaven. 
  
  Outside of work, I spend the bulk of my time taking photographs, spending time with friends and family and gaming.
about-image: /assets/imgs/hero-about.jpg
about-image-alt: Portrait of Marcus Relacion, designer and developer from Washington, DC
about-resume: https://siteleaf-cdn.s3.amazonaws.com/570e4dce3420fe01a900032f/assets/5717af4c3420fe073d000161.pdf?X-Amz-Expires=600&X-Amz-Date=20170731T021724Z&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAI2QYAGBXKTUSU2MA/20170731/us-east-1/s3/aws4_request&X-Amz-SignedHeaders=host&X-Amz-Signature=efff05bff2a0202b501064d335ce9eac442ac427d3f26d6fdaeae53fa19c4059

# Copyright Message
copyright: 2017 &amp; beyond, Marcus Relacion

# Excludes the following files & folders from being included in the site build
exclude:
  - Gemfile
  - Gemfile.lock
  - package.json
  - node_modules
  - gulpfile.js