---
title: Marcus Relacion, Designer & Developer
timezone: America/New_York
collections:
  notes:
    title: Notes
    output: false
  photos:
    title: Photos
    output: true
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: ''
    type: jobs
  values:
    is-current: 
    job-duration: 
    job-title: 
- scope:
    path: ''
    type: projects
  values:
    layout: single/project
    year: 
    image: 
    description: 
    main-content-text: 
    client: 
    role: 
    collaborators: []
    skills: []
- scope:
    path: ''
    type: photos
  values:
    layout: single/photo
    year: 
    image: 
    description: 
    main-content-text: 
    client: 
    role: 
    collaborators: []
    skills: []
description: Marcus Relacion is a designer and developer located in Alexandria, VA.
google-analytics: UA-111997703-1
copyright: 2017 &amp; beyond, Marcus Relacion
sass:
  sass_dir: _sass
  style: compressed
permalink: pretty
plugins:
- jekyll-feed
exclude:
- package.json
- gulpfile.js
- node_modules
- README.md
- Gemfile
- Gemfile.lock
- ".jekyll-metadata"
- ".sass-cache"
- CNAME
- ".DS_Store"
