---
title: Marcus Relacion, Designer & Developer
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
  values:
    image: 
exclude:
- package.json
- node_modules
- README.md
- Gemfile
- Gemfile.lock
- ".jekyll-metadata"
- ".sass-cache"
- ".DS_Store"
- package-lock.json
- package.json
plugins:
- jekyll-feed
sass:
  sass_dir: _sass
  style: compressed
permalink: pretty
encoding: utf-8
lang: en-US
logo: 
description: 
url: https://marcusrelacion.com
baseurl: 
repo: https://github.com/marcusrelacion/marcusrelacion.github.io
email: hello@marcusrelacion.com
